"""
Code Execution Tools

Provides tools for executing code in various programming languages.
"""

import subprocess
import logging
from typing import Dict, Any, Optional, List

from mirror_vanisher import MirrorVanisherManager
from errors_handler import handle_exception

logger = logging.getLogger(__name__)


class CodeExecutionTools:
    """Tools for executing code and scripts."""

    def __init__(self, manager: MirrorVanisherManager):
        """Initialize code execution tools.

        Args:
            manager: Mirror+Vanisher manager instance
        """
        self.manager = manager
        logger.info("CodeExecutionTools initialized")

    def execute_python_code(self, path: str, script_path: str, args: Optional[List[str]] = None, timeout: int = 30) -> Dict[str, Any]:
        """Execute a Python script in the specified directory.

        Args:
            path: Working directory (mirror+vanisher)
            script_path: Path to Python script relative to working directory
            args: Optional command-line arguments
            timeout: Execution timeout in seconds

        Returns:
            Execution result with stdout, stderr, and return code
        """
        try:
            resolved_path = self.manager.resolve_path(path)
            if not resolved_path:
                return {'success': False, 'error': f'Path not found: {path}'}

            script_file = resolved_path / script_path
            if not script_file.exists():
                return {'success': False, 'error': f'Script not found: {script_path}'}

            args = args or []
            command = ['python3', str(script_file)] + args

            result = subprocess.run(
                command,
                cwd=str(resolved_path),
                capture_output=True,
                text=True,
                timeout=timeout
            )

            return {
                'success': result.returncode == 0,
                'return_code': result.returncode,
                'stdout': result.stdout,
                'stderr': result.stderr,
                'command': ' '.join(command),
                'working_directory': str(resolved_path)
            }

        except subprocess.TimeoutExpired:
            return {'success': False, 'error': f'Execution timed out after {timeout} seconds'}
        except Exception as e:
            handle_exception(e, context={'function': 'execute_python_code', 'path': path, 'script': script_path})
            return {'success': False, 'error': str(e)}

    def execute_shell_command(self, path: str, command: str, timeout: int = 30) -> Dict[str, Any]:
        """Execute a shell command in the specified directory.

        Args:
            path: Working directory (mirror+vanisher)
            command: Shell command to execute
            timeout: Execution timeout in seconds

        Returns:
            Execution result with stdout, stderr, and return code
            
        Security Note:
            This function uses shell=True which can be a security risk if the 
            command contains unsanitized user input. Ensure commands are from 
            trusted sources only. This is acceptable in a controlled development 
            environment where commands are generated by the LLM for 
            mirror+vanisher directories only.
        """
        try:
            resolved_path = self.manager.resolve_path(path)
            if not resolved_path:
                return {'success': False, 'error': f'Path not found: {path}'}

            # WARNING: shell=True is used for command flexibility
            # Commands are executed in controlled mirror+vanisher directories only
            result = subprocess.run(
                command,
                cwd=str(resolved_path),
                capture_output=True,
                text=True,
                timeout=timeout,
                shell=True
            )

            return {
                'success': result.returncode == 0,
                'return_code': result.returncode,
                'stdout': result.stdout,
                'stderr': result.stderr,
                'command': command,
                'working_directory': str(resolved_path)
            }

        except subprocess.TimeoutExpired:
            return {'success': False, 'error': f'Command timed out after {timeout} seconds'}
        except Exception as e:
            handle_exception(e, context={'function': 'execute_shell_command', 'path': path, 'command': command})
            return {'success': False, 'error': str(e)}

    def execute_javascript_code(self, path: str, script_path: str, args: Optional[List[str]] = None, timeout: int = 30) -> Dict[str, Any]:
        """Execute a JavaScript/Node.js script in the specified directory.

        Args:
            path: Working directory (mirror+vanisher)
            script_path: Path to JavaScript file relative to working directory
            args: Optional command-line arguments
            timeout: Execution timeout in seconds

        Returns:
            Execution result with stdout, stderr, and return code
        """
        try:
            resolved_path = self.manager.resolve_path(path)
            if not resolved_path:
                return {'success': False, 'error': f'Path not found: {path}'}

            script_file = resolved_path / script_path
            if not script_file.exists():
                return {'success': False, 'error': f'Script not found: {script_path}'}

            args = args or []
            command = ['node', str(script_file)] + args

            result = subprocess.run(
                command,
                cwd=str(resolved_path),
                capture_output=True,
                text=True,
                timeout=timeout
            )

            return {
                'success': result.returncode == 0,
                'return_code': result.returncode,
                'stdout': result.stdout,
                'stderr': result.stderr,
                'command': ' '.join(command),
                'working_directory': str(resolved_path)
            }

        except subprocess.TimeoutExpired:
            return {'success': False, 'error': f'Execution timed out after {timeout} seconds'}
        except Exception as e:
            handle_exception(e, context={'function': 'execute_javascript_code', 'path': path, 'script': script_path})
            return {'success': False, 'error': str(e)}

    def execute_code_snippet(self, path: str, language: str, code: str, timeout: int = 30) -> Dict[str, Any]:
        """Execute a code snippet in the specified language.

        Args:
            path: Working directory (mirror+vanisher)
            language: Programming language (python, javascript, bash)
            code: Code snippet to execute
            timeout: Execution timeout in seconds

        Returns:
            Execution result with stdout, stderr, and return code
        """
        try:
            resolved_path = self.manager.resolve_path(path)
            if not resolved_path:
                return {'success': False, 'error': f'Path not found: {path}'}

            # Create temporary file for code snippet
            temp_file = resolved_path / f'_temp_snippet.{language}'
            temp_file.write_text(code)

            try:
                if language == 'python':
                    result = self.execute_python_code(path, str(temp_file.name), timeout=timeout)
                elif language in ['javascript', 'js']:
                    result = self.execute_javascript_code(path, str(temp_file.name), timeout=timeout)
                elif language == 'bash':
                    result = self.execute_shell_command(path, f'bash {temp_file.name}', timeout=timeout)
                else:
                    return {'success': False, 'error': f'Unsupported language: {language}'}

                return result
            finally:
                # Clean up temp file
                if temp_file.exists():
                    temp_file.unlink()

        except Exception as e:
            handle_exception(e, context={'function': 'execute_code_snippet', 'path': path, 'language': language})
            return {'success': False, 'error': str(e)}
